//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataType
    {
        public long Id { get; set; }
        public bool Bit { get; set; }
        public Nullable<decimal> Decimal { get; set; }
        public Nullable<int> Integer { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Numeric { get; set; }
        public Nullable<short> Smallint { get; set; }
        public string Enum { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
